version: '3'

volumes:
  dbdata:

services:
  postgres:
    image: postgres:15
    container_name: postgresdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: house-keeping
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backupLocalData.sql:/docker-entrypoint-initdb.d/backupLocalData.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./housekeepingBack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/house-keeping
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  frontend:
    image: housekeeping
    build:
      context: ./house-keeping-Front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8082:80"
    depends_on:
      - backend

